### PR TITLE
Update hello_world.html with french greeting

### PR DESCRIPTION
**Pull request by TestCharles02**

### CODE REVIEW

**Comment by CharlesWong020** [comment]
Spelling error please change

**Review by CharlesWong020 — CHANGES_REQUESTED** [review]
Please fix typo in "Bonjour Mode"

**Comment by TestCharles02** [comment]
I have fixed typo. Please re-review. @CharlesWong020

**Review by CharlesWong020 — APPROVED** [review]
Good job!

**Pull request merged**
